# MATH30100 Assignment 1 - 19404354

## Question 4 - LU Decomposition

### b) Sequence of row operations

In [32]:
import numpy as np

In [33]:
A=np.array([[1,9,4],[0,4,3],[5,4,4.0]])
n=3
b=np.array([1,2,3])

In [34]:
L=np.identity(n)
U=np.array(A)
y=np.array(b)

In [35]:
# We can operate a sequence of row operations using a loop which reiterates for each row to get L and U
for k in range(0,n):
    for i in range(k+1,n):
        L[i,k]=U[i,k]/U[k,k]
        U[i,:]=U[i,:]-L[i,k]*U[k,:]
        y[i]=y[i]-L[i,k]*y[k]

In [36]:
L

array([[  1.  ,   0.  ,   0.  ],
       [  0.  ,   1.  ,   0.  ],
       [  5.  , -10.25,   1.  ]])

In [37]:
U

array([[ 1.  ,  9.  ,  4.  ],
       [ 0.  ,  4.  ,  3.  ],
       [ 0.  ,  0.  , 14.75]])

In [9]:
L@U

array([[1., 9., 4.],
       [0., 4., 3.],
       [5., 4., 4.]])

### d) scipy.linalg.lu

In [8]:
import scipy.linalg

In [38]:
(P,L,U)=scipy.linalg.lu(A)

In [39]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [40]:
L

array([[1.        , 0.        , 0.        ],
       [0.2       , 1.        , 0.        ],
       [0.        , 0.48780488, 1.        ]])

In [41]:
U

array([[5.        , 4.        , 4.        ],
       [0.        , 8.2       , 3.2       ],
       [0.        , 0.        , 1.43902439]])

In [42]:
P@L@U

array([[1., 9., 4.],
       [0., 4., 3.],
       [5., 4., 4.]])

## Question 5 - QR Decomposition

### c) numpy.linalg.qr

In [43]:
(Q,R) = np.linalg.qr(A)

In [44]:
Q

array([[-0.19611614, -0.87794634, -0.43674785],
       [-0.        , -0.44539717,  0.8953331 ],
       [-0.98058068,  0.17558927,  0.08734957]])

In [45]:
R

array([[-5.09901951, -5.68736792, -4.70678724],
       [ 0.        , -8.98074864, -4.14561978],
       [ 0.        ,  0.        ,  1.28840617]])

In [46]:
Q@R

array([[1., 9., 4.],
       [0., 4., 3.],
       [5., 4., 4.]])

## Question 6 - Singular Value Decompisition

### b) numpy.linalg.svd

In [47]:
(U,S,V)=np.linalg.svd(A)

In [48]:
U

array([[-0.76435426, -0.46257899, -0.44920291],
       [-0.37814873, -0.24269051,  0.89336715],
       [-0.52227015,  0.85271449,  0.01057787]])

In [49]:
Sigma=np.diag(S)
Sigma

array([[12.67651947,  0.        ,  0.        ],
       [ 0.        ,  4.25554738,  0.        ],
       [ 0.        ,  0.        ,  1.09369582]])

In [50]:
V

array([[-0.26629589, -0.82679349, -0.49547858],
       [ 0.89318556, -0.40491029,  0.19562007],
       [-0.36236178, -0.39046149,  0.84630595]])

In [51]:
U@Sigma@V

array([[ 1.0000000e+00,  9.0000000e+00,  4.0000000e+00],
       [-5.6575961e-16,  4.0000000e+00,  3.0000000e+00],
       [ 5.0000000e+00,  4.0000000e+00,  4.0000000e+00]])